@echo off
set /a r=%random% %% 50
if %r%==0 echo Smith
if %r%==1 echo Johnson
if %r%==2 echo Williams
if %r%==3 echo Brown
if %r%==4 echo Jones
if %r%==5 echo Garcia
if %r%==6 echo Miller
if %r%==7 echo Davis
if %r%==8 echo Rodriguez
if %r%==9 echo Martinez
if %r%==10 echo Hernandez
if %r%==11 echo Lopez
if %r%==12 echo Gonzalez
if %r%==13 echo Wilson
if %r%==14 echo Anderson
if %r%==15 echo Thomas
if %r%==16 echo Taylor
if %r%==17 echo Moore
if %r%==18 echo Jackson
if %r%==19 echo Martin
if %r%==20 echo Lee
if %r%==21 echo Perez
if %r%==22 echo Thompson
if %r%==23 echo White
if %r%==24 echo Harris
if %r%==25 echo Sanchez
if %r%==26 echo Clark
if %r%==27 echo Ramirez
if %r%==28 echo Lewis
if %r%==29 echo Robinson
if %r%==30 echo Walker
if %r%==31 echo Young
if %r%==32 echo Allen
if %r%==33 echo King
if %r%==34 echo Wright
if %r%==35 echo Scott
if %r%==36 echo Torres
if %r%==37 echo Nguyen
if %r%==38 echo Hill
if %r%==39 echo Flores
if %r%==40 echo Green
if %r%==41 echo Adams
if %r%==42 echo Nelson
if %r%==43 echo Baker
if %r%==44 echo Hall
if %r%==45 echo Rivera
if %r%==46 echo Campbell
if %r%==47 echo Mitchell
if %r%==48 echo Carter
if %r%==49 echo Roberts
