@echo off
set /a r=%random% %% 50
if %r%==0 echo James
if %r%==1 echo John
if %r%==2 echo Robert
if %r%==3 echo Michael
if %r%==4 echo William
if %r%==5 echo David
if %r%==6 echo Richard
if %r%==7 echo Joseph
if %r%==8 echo Thomas
if %r%==9 echo Charles
if %r%==10 echo Christopher
if %r%==11 echo Daniel
if %r%==12 echo Matthew
if %r%==13 echo Anthony
if %r%==14 echo Mark
if %r%==15 echo Donald
if %r%==16 echo Steven
if %r%==17 echo Paul
if %r%==18 echo Andrew
if %r%==19 echo Joshua
if %r%==20 echo Kenneth
if %r%==21 echo Kevin
if %r%==22 echo Brian
if %r%==23 echo George
if %r%==24 echo Edward
if %r%==25 echo Ronald
if %r%==26 echo Timothy
if %r%==27 echo Jason
if %r%==28 echo Jeffrey
if %r%==29 echo Ryan
if %r%==30 echo Jacob
if %r%==31 echo Gary
if %r%==32 echo Nicholas
if %r%==33 echo Eric
if %r%==34 echo Jonathan
if %r%==35 echo Stephen
if %r%==36 echo Larry
if %r%==37 echo Justin
if %r%==38 echo Scott
if %r%==39 echo Brandon
if %r%==40 echo Frank
if %r%==41 echo Benjamin
if %r%==42 echo Gregory
if %r%==43 echo Samuel
if %r%==44 echo Raymond
if %r%==45 echo Patrick
if %r%==46 echo Alexander
if %r%==47 echo Jack
if %r%==48 echo Dennis
if %r%==49 echo Jerry
